# Generated by Django 6.0.1 on 2026-01-26 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Номи фан')),
                ('description', models.TextField(blank=True, verbose_name='Тавсифи фан')),
                ('timer_minutes', models.PositiveIntegerField(default=5, verbose_name='Вақт (дақиқа)')),
            ],
            options={
                'verbose_name': 'Фан',
                'verbose_name_plural': 'Фанҳо',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Хол')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Ҳамаи саволҳо')),
                ('level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Сатҳи дониш')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Тавсифи AI')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Тавсияи AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject', verbose_name='Фан')),
            ],
            options={
                'verbose_name': 'Натиҷа',
                'verbose_name_plural': 'Натиҷаҳо',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Матни савол')),
                ('difficulty', models.CharField(choices=[('easy', 'Осон'), ('medium', 'Миёна'), ('hard', 'Мушкил')], default='easy', max_length=10, verbose_name='Сатҳи савол')),
                ('option_a', models.CharField(max_length=255, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Вариант B')),
                ('option_c', models.CharField(blank=True, max_length=255, verbose_name='Вариант C')),
                ('option_d', models.CharField(blank=True, max_length=255, verbose_name='Вариант D')),
                ('correct_option', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Ҷавоби дуруст')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subject', verbose_name='Фан')),
            ],
            options={
                'verbose_name': 'Савол',
                'verbose_name_plural': 'Саволҳо',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Истифодабаранда')),
                ('subjects', models.ManyToManyField(blank=True, related_name='users', to='quiz.subject', verbose_name='Фанҳои иҷозатдодашуда')),
            ],
            options={
                'verbose_name': 'Профил',
                'verbose_name_plural': 'Профилҳо',
            },
        ),
    ]
